### ISSUE TITLE
v2 is available at packagist

### ISSUE THREAD

**Issue by masakik** [tomsix/laravel-components-library#18]
Hi, I have installed 1 day ago from composer and it installed v2. Here I saw it is a pre-release but packagist understood as a standard one.

**Comment by tomsix** [comment]
Bedankt voor de melding. Ik zal proberen de pre-release versie te verwijderen

**Comment by masakik** [comment]
I am not sure about this but you can remove the tag v2.0.0 and add another one similar to v2.0.0-dev so it stays available to contributors who wants to download specific 

https://getcomposer.org/doc/04-schema.md#version

**Comment by tomsix** [comment]
Perhaps it is better that way. I will adjust it. Thanks for the information

**Comment by masakik** [comment]
By the way, when you expect to release v2?

**Comment by tomsix** [comment]
I released v2 just an hour ago 😃
