### ISSUE TITLE
Unexpected 'iterable' 

### ISSUE THREAD

**Issue by trygveb** [tomsix/laravel-components-library#5]
When trying to use the model-select component I get the follow error message:

`syntax error, unexpected 'iterable' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at /var/www/.../vendor/tomsix/laravel-components-library/src/View/Components/Form/Select.php:13) `

This occurs only in my production environment (Linode server Ubuntu 18.04.4 LTS with PHP 7.4.6 and Laravel 7.28.3)
In my development server (a Homestead Vagrant Box on Windows 10, with Ubuntu 18.04.4 LTS, PHP 7.4.4 and Laravel 7.28.3), this is working fine.

The Blade templates are of course identical in the two environments but  not the model data (but I can't see that this should make any difference).

**Comment by tomsix** [comment]
I cannot find a direct cause of that error.

I changed the type from `iterable` to `array`. Hopefully this will solve the problem. This is now in a pre-release
